# Site settings
description: Academic Website of Raphael Spreitzer, SGS, Graz, Austria
keywords: Raphael Spreitzer, Security, Privacy, SGS
title: Raphael Spreitzer | SGS

author: Raphael Spreitzer
authorimg: images/rs.png
authoroccup: Principal Security Expert
#inst: Secure Products & Systems
#insturl: 
uni: SGS (Cybersecurity Services)
uniurl: https://www.sgs.com/en/campaigns/sgs-cybersecurity-services
email: raphael.spreitzer@gmail.com

twitter: rspreitzer_
github:  rspreitzer
dblp: hd/s/Spreitzer:Raphael
scholar: rAckLssAAAAJ
orcid: 0000-0001-6844-292X
linkedin: raphael-spreitzer
xing: Raphael_Spreitzer


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  - proc
  - jour
  - theses
  - talks
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock

