# Site settings
description: Academic Website of Raphael Spreitzer, IAIK, Graz University of Technology, Graz, Austria
keywords: Raphael Spreitzer, Security, Privacy, IAIK, Graz University of Technology
title: Raphael Spreitzer | IAIK, Graz University of Technology

author: Raphael Spreitzer
authorimg: images/rs.png
authoroccup: Researcher (Security & Privacy)
inst: IAIK
insturl: https://www.iaik.tugraz.at
uni: Graz University of Technology
uniurl: https://www.tugraz.at
email: raphael.spreitzer@iaik.tugraz.at

twitter: rspreitzer_
github:  rspreitzer
vcard: https://online.tugraz.at/tug_online/visitenkarte.show_vcard?pPersonenId=FB1EB244100F45C6&pPersonenGruppe=3
dblp: hd/s/Spreitzer:Raphael
scholar: rAckLssAAAAJ
orcid: 0000-0001-6844-292X
linkedin: raphael-spreitzer
xing: Raphael_Spreitzer


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  - proc
  - jour
  - theses
  - talks
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock

